version: '3.9'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bot:
    image: cube-system-bot:2
    environment:
      DB_NAME: postgres_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: database
      DB_PORT: 5432
      TOKEN: 6463599178:AAGpifGcbscRtvREdFvwqjloa0_PSJGSzsk
      ADMIN_IDS: 603789543,991027824
      DEVICE: Laptop


volumes:
  pgdata:
